=== cvacar/MoOtherPublicRepo/web/WEB-INF/tasks/linx_taskdef_3_1.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
linx_taskdef_3_1.dtd

Linx Task Definition DTD 3.1.1

(c)Copyright 2004 Wildtype Informatics LLC All rights reserved.
 - Updated Dec 2008 to ensure all Linx elements/attributes were included in DTD.  TR Wildtype Informatics

This document is the DTD for Linx 3.x task definition XML files.

Task definitions are loaded by the Linx server on start-up
to configure the rules of one workflow (lab process).

REVISION HISTORY

11/25/2010	TJR/WT	v3.1.1	Added "saveOnce" attribute to addAsAppFile node for an item
											saveOnce="true" in conjunction with itemType attribute new="optional"
										 	will allow DB to assign a single applicationFileId to all rows imported
										 	in a bulk insert transaction for a single import file
-->

<!--
linx

Task defs may be divided among multiple .xml files or inside ZIP files,
but all must start with the parent 'linx' element, and contain at least
one 'task' element under 'linx'.
-->
<!ELEMENT linx ( task+ ) >

<!--
task

Tasks are steps in a process or workflow, each uniquely named.
-->
<!ELEMENT task ( client, server ) >
<!--
task attributes

If a custom JSP or HTML page should be displayed to the user, the optional
'pg' attribute will specify the path, relative to the Linx directory. If
pg='default', Linx will attempt to construct the JSP name by using the task name
with underscores. Example: 'PgTask_Make_Box_A.jsp'.

Likewise, if a custom servlet should perform processing on the collected data,
optional 'svURL' attribute will specify the URL to the servlet,
exactly as mapped in the server container's web.xml (NOT the name of a
servlet class).
Example of a web.xml mapping (slash would be included in attribute value):

<servlet-mapping>
    <servlet-name>Task_Make_Box_A</servlet-name>
    <url-pattern>/Task_Make_Box_A</url-pattern>
</servlet-mapping>
-->
<!ATTLIST task name CDATA #REQUIRED
               taskVersion NMTOKEN #REQUIRED
               pg CDATA #IMPLIED
               svURL CDATA #IMPLIED
               taskClass CDATA #IMPLIED>

<!--
client

Task user interfaces can be displayed automatically by the Linx server based on
widgets specified in the 'client' section of the task def.
Alternately, developers may override the display in any manner desired.
-->
<!ELEMENT client ( displayItems ) >
<!ATTLIST client clientVersion CDATA #REQUIRED >

<!ELEMENT displayItems ( displayItem* ) >
<!--
displayItem

Each displayItem represents a widget used to collect data from the user.

The widgets enumerated here are those supported by Linx, which will
automatically draw HTML based on the widget def. This DTD can be updated
with more widget names as new widgets are developed for specific data collection needs.

If 'label' is missing, Linx will use this displayItem's itemType.
Attribute 'rowcount' is used only for 'table' widget,
for which it specifies the number of rows to display.
Attribute 'scrollable' applies only to text and 'textarea' widget.
Attribute 'action' applies only to button-type widgets.
Attribute 'persist' signals Linx that the widget's value should not be erased
between displays of the task page.
Attribute 'uppercase' applies to all text-type widgets.

-->
<!ELEMENT displayItem ( sql?, values?, value?, columns?, group?) >
<!ATTLIST displayItem itemType NMTOKEN #REQUIRED
                      widget (button|savebutton|verifybutton|buttongroup|dropdown|text|textinput|
                              label|textarea|filebrowse|table|rowset|rowsets|rawhtml|checkbox|
                              radio|hidden|passFailTable|rowColTable|itemLabel|message|inputtable|
                              rowsetNaveControls|rowsetRow|rowsetsItor|rowsetTable|
                              rowsetTableCompact|showObject|textbox|password|href|datepicker|datetimepicker|
                              rowset_sort|rowsets_sort) #REQUIRED
                      label CDATA #IMPLIED
                      uppercase (true) #IMPLIED
                      columnHeader CDATA #IMPLIED
                      rowCount CDATA #IMPLIED
                      action CDATA #IMPLIED
                      persist (true) #IMPLIED
                      scrollable (true) #IMPLIED
                      maxLength NMTOKEN #IMPLIED
                      minLength NMTOKEN #IMPLIED
                      rowcount NMTOKEN #IMPLIED
                      scrollSize NMTOKEN #IMPLIED
                      accept NMTOKEN #IMPLIED
                      selected (true|false) #IMPLIED
                      visible (true|false) #IMPLIED
                      dateFormat CDATA #IMPLIED>
<!--
value, values

If the displayItem should display a default value to the user,
these optional values/value elements will be included. If only
one value is needed (for example, in a textinput box), 'value' may
appear without the parent 'values'.
-->
<!ELEMENT values ( value+ ) >
<!ELEMENT value ( #PCDATA ) >
<!ATTLIST value selected (true|false) #IMPLIED>

<!-- Optional element 'sql' contains a valid SQL statement (or stored proc call)
that will be executed to populate values in this widget, usually a dropdown-->
<!ELEMENT sql (#PCDATA ) >
<!--
group

Two widgets, 'radio' and 'button', may appear in groups. This element
specifies the members of each group.

Groups are important for radio buttons, to ensure that only one value
may be selected at a time per group name. Default radio button can
be set with 'selected' attribute. Do NOT set selected=false for other
group members.
-->
<!ELEMENT group ( member+ ) >
<!ATTLIST group name NMTOKEN #REQUIRED >

<!ELEMENT member EMPTY >
<!ATTLIST member label NMTOKEN #REQUIRED
                 value NMTOKEN #REQUIRED
                 selected (true) #IMPLIED
                 action NMTOKEN #IMPLIED >
<!--
columns

Linx offers a simple textbox-field table for which column names
as well as rowcount may be specified.
-->
<!ELEMENT columns ( column+ ) >
<!ELEMENT column ( #PCDATA ) >


<!--
server

Linx merges values collected from the client into the 'server' section
of the task def wherever itemTypes match the submitted values' itemTypes.

Values may be automatically processed by Linx according to
rules configured here, or partially or completely overridden by custom code.
-->
<!ELEMENT server ( items ) >

<!ELEMENT items ( item* ) >

<!--
item

Each item provides a value required to update the state of the workflow,
usually to move items (containers) from one step to another in the lab process.
Example items of type 'container' are: plastic microtiter plates, work orders, samples.

Values can also be collected that are not containers, but help provide
a complete audit trail or aid in decisions about routing true containers.
Example 'string' or 'number' items: a reagent's lot identifier,
the name of a thermocycler program, an incubation temperature.
-->
<!ELEMENT item ( allowQueue*, addAsContent*, queueTo*, dequeueFrom*, addAsData*, addAsCondition*, addAsAppFile* ) >
<!--
item attributes

Items of type='container' are validated against the ITEMS table for existence,
unless the 'new' attribute is present. If new=y, the item may not already exist,
and will be created. If new=optional, the item may or may not exist; it will
be created if not.

If a mask attribute is present, Linx checks the item value
against the attribute's value, which must be a Java regular expression.
This feature is useful for validating barcode patterns.
Example of mask pattern:

mask="GS[0-9]{7}-NAA"

Barcode 'GS0000001-NAA' would qualify, but 'GT0000001-NAA' would generate an error.
-->
<!ATTLIST item itemType NMTOKEN #REQUIRED
               type (container|comment|string|number|condition|file) #REQUIRED
               mask CDATA #IMPLIED
               optional (true|false) #IMPLIED
               new (true|optional) #IMPLIED >

<!--
addAsContent

When this optional element appears under an item, the item's value(s) will
be added as a content to the item value(s) that appear under the target itemType
(after Linx merges the data). Only items of type='container' may be added as contents.
Contents of a source container will NOT be copied.

If contentType is missing, Linx will use this item's itemType as the new
contentType for the new CONTENTS record.

Coordinate is often a simple '0', which by Linx convention means the new content
belongs to the entire target container. Coordinate may also specify a well or any other
physical or virtual location ('A01' or 'blue').
-->
<!ELEMENT addAsContent EMPTY >
<!ATTLIST addAsContent contentType NMTOKEN #IMPLIED
                       appliesTo NMTOKEN #REQUIRED
                       coordinate NMTOKEN #REQUIRED >
<!--
addAsData

When this optional element appears under an item, the item's value(s) will
be added as data to the item value(s) that appear under the target itemType
(after Linx merges the data). If appliesTo='task', the new data record will
apply to the entire task rather than a target container. This feature is useful
for recording variables that affect an entire task, e.g. which instrument was used.

If dataType is missing, Linx will use this item's itemType as the new
dataType for the new CONTENTS record (only 'data'/'dataType' fields are populated).

Coordinate is often a simple '0', which by Linx convention means the new data
belongs to the entire target item. Coordinate may also specify a well or any other
location, physical or virtual ('A01' or 'blue').
-->
<!ELEMENT addAsData EMPTY >
<!ATTLIST addAsData dataType NMTOKEN #IMPLIED
                    appliesTo NMTOKEN #REQUIRED
                    coordinate NMTOKEN #REQUIRED >
<!--
addAsCondition

When this optional element appears under an item, the item's value(s) will
be added as condition to the item value(s) that appear under the target itemType
(after Linx merges the data). If appliesTo='task', the new condition record will
apply to the entire task rather than a target container. This feature is useful
for recording variables that affect an entire task, e.g. which instrument was used.

If conditionType is missing, Linx will use this item's itemType as the
conditionType for the new CONDITIONS record.

Coordinate is often a simple '0', which by Linx convention means the condition
belongs to the entire target item. Coordinate may also specify a well or any other
location, physical or virtual ('A01' or 'blue').
-->
<!ELEMENT addAsCondition EMPTY >
<!ATTLIST addAsCondition conditionType NMTOKEN #IMPLIED
                         appliesTo NMTOKEN #REQUIRED
                         coordinate NMTOKEN #REQUIRED >
                         
<!--
addAsAppFile

When this optional element appears under an item, the item's value(s) will
be added as application file to the item value(s) that appear under the target itemType
(after Linx merges the data). 

If fileType is missing, Linx will use this item's itemType as the
fileType for the new APPLICATION_FILE record.

-->
<!ELEMENT addAsAppFile EMPTY >
<!ATTLIST addAsAppFile fileType NMTOKEN #IMPLIED
					   appliesTo NMTOKEN #REQUIRED
					  	saveOnce NMTOKEN #REQUIRED
                       validate NMTOKEN #REQUIRED
                       copyFileTo NMTOKEN #REQUIRED
                       mask NMTOKEN #IMPLIED
                       extcoord NMTOKEN #IMPLIED >
                         
<!--
copyContents

When this optional element appears under an item,
the contents of the item's value(s) will be copied as new contents
under the item value(s) that appear under the target ('appliesTo') itemType
(after Linx merges the data). Only items of type='container'
may have their contents copied. The source container itself is not added
as a content, but an ITEMHISTORY record tracks that these two containers
were in a copyContents transaction.

If contentType is missing, Linx will copy all contents of any contentType
from the source to the target container. Specifying a contentType is common
if, for example, only DNA Samples or only PCR products should be copied.

The attribute 'transferplan' MUST refer to an existing transferplan in the
TRANSFERPLANS table. Linx will copy any contents with coordinates that match
the coordinates in the transferplan. As a result, the wrong transferplan can
result in a successful transfer (no errors) that copies nothing because
the source plate and transferplan had no matching coordinates.
-->
<!ELEMENT copyContents EMPTY >
<!ATTLIST copyContents contentType NMTOKEN #IMPLIED
                       appliesTo NMTOKEN #REQUIRED
                       transferPlan NMTOKEN #REQUIRED >
<!--
allowQueue

Each optional 'allowQueue' node is processed by Linx to override the default requirement
that an item be on the queue for the task defined in THIS task def
before processing may continue. Only type='container' items are affected.

Commonly, the value 'any' will appear, which flags Linx to skip queue validation
for this item. This feature is helpful during testing,
but is not ideal in production LIMS when the workflow should be able
to anticipate which queues will hold an item at the time this step is reached.
-->
<!ELEMENT allowQueue ( #PCDATA ) >
<!--
queueTo

The 'queueTo' element is used to advance the state of the workflow by adding
the given item to the named queue. Only type='container' items are affected.
The target queue need not be a valid task name, nor exist yet in the QUEUES table.
An item can be queued multiple times, and it will appear on the target queue
multiple times. (However, see 'dequeueFrom'.)

Queueing is decoupled from dequeueing, for ultimate control.
-->
<!ELEMENT queueTo ( #PCDATA ) >
<!--
deqeueFrom

The 'dequeueFrom' element is used to advance the state of the workflow by removing
this item's value(s) from the named queue. Only type='container' items are affected.
No error is thrown if the named queue does not exist or the item is not on the queue.
Dequeueing is not required.

Dequeueing an item dequeues ALL instances of the item from the target queue.
-->
<!ELEMENT dequeueFrom ( #PCDATA ) >

=== cvacar/MoOtherPublicRepo/tags/v2.0.3/web/WEB-INF/tasks/Linx_Admin_Tasks.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE linx SYSTEM "../config/linx_taskdef_3_1.dtd">
<!-- 9/30/2010  TJR Updates made to support Linx v3.5 release 
					 TJR fixes to Manage Settings so "delete" and "update" work reliably
-->

<linx>
     <task name="Authenticate" taskVersion="1.0" pg="default" svURL="default">
      <client clientVersion="1.0">
        <displayItems></displayItems>
      </client>
      <server>
        <items></items>
      </server>
    </task>
	<task name="Enter Maintenance Mode" taskVersion="1.0" pg="default"
		svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
				<displayItem itemType="eta" 
          				label="Date/time LIMS will be online again:" 
          				widget="datetimepicker"
          				dateFormat='mm/dd/yyyy, h:MM TT' />
				<!--   <displayItem itemType="eta" label="Date/time LIMS will be online again:"
					widget="textinput" minLength="20" maxLength="50" />
				-->
				<displayItem itemType="submit" label="Refuse future connections"
					widget="button" action="Start" />
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>
         <task name="Manage Logs" taskVersion="1.0" pg="default" svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
           <displayItem itemType="Tables" widget="rowsets"/>
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>
         <task name="Manage Resources" taskVersion="1.0" pg="default" svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
           <displayItem itemType="newResource" 
                        label="Resource" 
                        widget="textinput" 
                        uppercase="true" 
                        minLength="20" 
                        maxLength="50"/>
           <displayItem itemType="newResourceType" 
                        label="Type" 
                        widget="dropdown" 
                        action="Add">
                        	<values>
                        	<value>Shaker</value>
                        	<value>Thermocylcer</value>
                        	<value>Freezer</value>
                        	<value>-80 Freezer</value>
                        	<value>Oven</value>
                        	</values>
            </displayItem>
           <displayItem itemType="status" 
                        label="Status" 
                        widget="dropdown" 
                        action="Add">
                        	<values>
                        	<value>Online</value>
                        	<value>Offline</value>
                        	<value>Offline for repair</value>
                        	</values>
             </displayItem>
            <displayItem itemType="Tables" widget="rowsets"/>
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>
	<!-- Name this task "Manage Settings" if users are NOT allowed to EDIT settings, 
	     otherwise add "NOT USED" to its name -->
	<task name="Manage Settings NOT USED" taskVersion="1.0" pg="default" svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
				<displayItem itemType="Label1" widget="label" label=" ">
            <value>(Optional) Select type of new value</value> 
     </displayItem> 
				<displayItem itemType="NewType" label=" " widget="dropdown"
					visible="true" action="Go">
	               <values>
	                 <value selected="true">(Select)</value>
	               	 <value>Parent Type</value>
	               	 <value>Setting Name</value>
	               	 <value>Setting Value</value>
	               </values>
	      </displayItem>
				<displayItem itemType="ParentType" label="Select Parent Type"
					widget="dropdown" visible="false">
                <sql>select distinct parentType from PARENTTYPE order by parentType</sql>
	   </displayItem>
				<displayItem itemType="Get" label=" " widget="button"
					action="Get Setting Names" visible="false" />
				<displayItem itemType="AppValueType" label="Select Setting Name"
					widget="dropdown" visible="false">
	               <values>
	               		<value selected="true">(Select)</value>
	               </values>
	             </displayItem>
				<displayItem itemType="NewValue" label="Enter new value"
					widget="textinput" uppercase="false" minLength="50" maxLength="100"
	                    visible="false"/>
				<displayItem itemType="Add" label=" " widget="button"
					action="Add" visible="false" />
				<displayItem itemType="Placeholder" widget="label"
					label=" " />
				<displayItem itemType="Settings" widget="rowsets_sort" />
			</displayItems>
		</client>
		<server>
			<items>
			</items>
		</server>
	</task>

	<!-- Name this task "Manage Settings" if users are allowed to EDIT settings, 
	     otherwise add "NOT USED" to its name -->
	<task name="Manage Settings" taskVersion="1.0" pg="default"
		svURL="custom">
		<client clientVersion="1.0">
			<displayItems>
				<displayItem itemType="Label1" widget="label" label=" ">
					<value>(Optional)</value>
				</displayItem>
				<displayItem itemType="Label2" widget="label" label=" ">
					<value>
						To EDIT or DELETE existing setting, select the desired row in the table below.
						Then use the "Update Setting" or "Delete Setting" button to update table.
         			</value>
				</displayItem>
				
				<displayItem itemType="Placeholder1" widget="label" label=" " />
				
				<displayItem itemType="Label3" widget="label" label=" ">
					<value>
						(To Edit Setting) Enter new setting value for selected row
         			</value>
				</displayItem>
				<displayItem itemType="newSetting" label=" " widget="textinput"
					minLength="20" maxLength="200" />
				<displayItem itemType="UpdateSetting" label=" " widget="button"
					action="Update Setting" />
					
				<displayItem itemType="DeleteSetting" label=" " widget="button"
					action="Delete Setting" />
				
				<displayItem itemType="Placeholder2" widget="label" label=" " />	
				<displayItem itemType="Label4" widget="label" label=" ">
					<value>(Optional)</value>
				</displayItem>
				<displayItem itemType="Label5" widget="label" label=" ">
					<value>
						To ADD new setting, select "Parent Type" or
						"Setting Name" in dropdown below.
         			</value>
				</displayItem>
				
				<displayItem itemType="NewType" label=" " widget="dropdown"
					visible="true" action="Go">
					<values>
						<value selected="true">(Select)</value>
						<value>Parent Type</value>
						<value>Setting Name</value>
						<value>Setting Value</value>
					</values>
				</displayItem>
				<displayItem itemType="ParentType" label="Select Parent Type"
					widget="dropdown" visible="false">
					<sql>
						select distinct parentType from PARENTTYPE
						order by parentType
         				</sql>
				</displayItem>
				<displayItem itemType="Get" label=" " widget="button"
					action="Get Setting Names" visible="false" />
				<displayItem itemType="AppValueType" label="Select Setting Name"
					widget="dropdown" visible="false">
					<values>
						<value selected="true">(Select)</value>
					</values>
				</displayItem>
				<displayItem itemType="NewValue" label="Enter new value"
					widget="textinput" uppercase="false" minLength="50" maxLength="100"
                        visible="false"/>
				<displayItem itemType="Add" label=" " widget="button"
					action="Add" visible="false" />
				<displayItem itemType="Placeholder" widget="label"
                         label=" "/>                        
				
				<displayItem itemType="Settings" widget="rowsets_sort" />
				
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>

         <task name="Manage Users" taskVersion="1.0" pg="default" svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
          <displayItem itemType="Tables" widget="rowsets"/>
				<displayItem itemType="newUser" label="New User" widget="textinput"
					uppercase="false" minLength="20" maxLength="50" />
				<displayItem itemType="pass" label="Password" widget="password"
					uppercase="false" minLength="20" maxLength="50" />
				<displayItem itemType="passConfirm" label="Confirm Password"
					widget="password" uppercase="false" minLength="20" maxLength="50" />
				<displayItem itemType="active" label="Active" widget="checkbox"
					selected="true" />
				<displayItem itemType="addUser" label="Add New User"
					widget="button" action="Add User" />
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>
    
</linx>

=== cvacar/MoOtherPublicRepo/tags/v2.0.3/web/WEB-INF/tasks/DatePickerTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE linx SYSTEM "linx_taskdef_3_1.dtd"> -->

<!-- 
 NOTE: if both a rowset table with date[time]picker objects are used on the same page as individual
          date[time]picker objects the first object created will set the dateFormat for all other 
          objects of the same class.  datePicker can have a different format from dateTimePicker on
          the page, but all like objects will share the same format.  
          
dateFormat:
	datePicker and dateTimePicker don't handle date formats exactly the same.
	e.g.
	datePicker: 'y' = 2 digit year, 'yy' = 4 digit year
	dateTimePicker: 'yy' = 2 digit year, 'yyyy' = 4 digit year
	
	See jQuery documentation for datePicker widget date format options
	See standard JavaScript dateFormat documentation for dateTimePicker widget date format options
 -->

<linx>
     <task name="DatePicker Test" taskVersion="1.0" pg="default" svURL="custom">
      <client clientVersion="1.0">
        <displayItems>
        
        	<displayItem itemType="Tables" widget="rowsets" />
        	
        	 <!-- Can use any valid 'jquery datepicker' date format-->
        	          	
             <displayItem itemType="DatePicker1" 
          				label="DatePicker1" 
          				widget="datepicker"
          				dateFormat='mm/dd/y' />
          				
          	 <displayItem itemType="DatePicker2" 
          				label="DatePicker1" 
          				widget="datepicker"
          				dateFormat='mm-dd-yy' />
          	
          	<!-- Can use any valid 'javascript' date format-->
          				
             <displayItem itemType="DateTimePicker1" 
          				label="DateTimePicker1" 
          				widget="datetimepicker"
          				dateFormat='mm/dd/yy, h:MM:ss TT' />
          				
          	<displayItem itemType="DateTimePicker2" 
          				label="DateTimePicker2" 
          				widget="datetimepicker"
          				dateFormat='yyyyddmm, h:MM:ss TT' /> 
          				
           <displayItem itemType="Save" label=" " widget="button" action="save"/>
        </displayItems>
      </client>
      <server>
        <items>
        </items>
      </server>
    </task>
</linx>
